# This is a basic workflow to help you get started with Actions

name: Build PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Register GPG key
        run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889

      - name: Register installation source
        run: echo "deb http://miktex.org/download/ubuntu jammy universe" | sudo tee /etc/apt/sources.list.d/miktex.list

      - name: Install MiKTeX
        run: |
          sudo apt-get update
          sudo apt-get install miktex -y

      - name: Run miktexsetup to finish the setup
        run: sudo miktexsetup --shared=yes finish

      - name: Enable automatic package installation
        run: sudo initexmf --admin --set-config-value [MPM]AutoInstall=1

      - name: Build documents
        run: sudo bash build.sh



